config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  resources :laptops
  resources :beneficiaries
  resources :links

  get 'home/index'
  get 'links/index'
  get 'laptops/index'
  get 'beneficiaries/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
  validates :name, presence: true
  validates :identification_document, presence: true, length: { minimum: 9, maximum: 11 }
  validates :contact_number, presence: true
  validates :contract_type, presence: true, inclusion: { in: %w(contratado efetivo) }

  has_many :links

  def as_json(options = {})
    super(options.merge(include: :links))
  end
  

end

app/models/laptop.rb
class Laptop < ApplicationRecord
  validates :serial_number, presence: true, length: { is: 22 }
  validates :listed_number, presence: true, length: { is: 7 }
  validates :model, presence: true, inclusion: { in: %w(A515-54-5526 A515-54-55L0) }

  has_many :links

  def as_json(options = {})
    super(options.merge(include: :links))
  end
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :beneficiary
  belongs_to :laptop
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beneficiaries_controller.rb
class BeneficiariesController < ApplicationController
  def index
    @beneficiaries = Beneficiary.all

  end

  def show
    @beneficiary = Beneficiary.find(params[:id])
  end

  def new
    @beneficiary = Beneficiary.new
  end

  def create
    @beneficiary = Beneficiary.new(beneficiary_params)

    if @beneficiary.save
      redirect_to @beneficiary
    else
      render :new, status: :unprocessable_entity
    end
  end

  def linked?(beneficiary)
    if beneficiary.links.count > 0
       beneficiary.links.last.end_date == nil ? "Ninguem" : beneficiary.links.last.laptop.listed_number
    end
    "Ninguem"
  end


  private
    def beneficiary_params
      params.require(:beneficiary).permit(:name, :identification_document, :contact_number, :contract_type)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @laptops = Laptop.all
    @beneficiaries = Beneficiary.all
  end
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  def index
    @laptops = Laptop.all
  end

  def show
    @laptop = Laptop.find(params[:id])
  end

  def new
    @laptop = Laptop.new
  end

  def create
    @laptop = Laptop.new(laptop_params)

    if @laptop.save
      redirect_to @laptop
    else
      render :new, status: :unprocessable_entity
    end
  end


  private
    def laptop_params
      params.require(:laptop).permit(:serial_number, :listed_number, :model)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
    @laptops = Laptop.all.map do |laptop|
      laptop.links.empty? || laptop.links.last.end_date.nil?
    end
    @beneficiaries = Beneficiary.all

  end

  def show
    @link = Link.find(params[:id])
    @beneficiary = @link.beneficiary
    @laptop = @link.laptop
  end

  def new
    @laptops = []
    @beneficiaries = []
    @link = Link.new
    Laptop.all.each do |l|
      if l.links.count > 0
        if !l.links.last.end_date.nil?
            @laptops.push(l)
        end
      else
        @laptops.push(l)
      end
    end
    Beneficiary.all.each do |b|
      if b.links.count > 0
        if !b.links.last.end_date.nil?
            @beneficiaries.push(b)
        end
      else
        @beneficiaries.push(b)
      end
    end
  end

  def create
    @link = Link.new(link_params)
    @link.init_date = Date.today

    if @link.save
      redirect_to @link
    else
      render :new, status: :unprocessable_entity
    end
  end


  private
    def link_params
      params.require(:link).permit(:beneficiary_id, :laptop_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def linked? entity
    if entity.links.count > 0
      if entity.links.last.end_date == nil
        entity.class == Laptop ? entity.links.last.beneficiary.name.split(" ").first : entity.links.last.laptop.listed_number.insert(2,"-")
      else
        "Ninguem"
      end

    end

  end
end

app/helpers/beneficiaries_helper.rb
module BeneficiariesHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/laptops_helper.rb
module LaptopsHelper

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/beneficiaries/index.html.erb
<section class="container-fluid p-5">
    <div class="row h-100 justify-content-around">
        <div class="col-10 bg-whitesmoke p-0 border rounded">
            <div class="d-flex  bg-whitesmoke-titles">
                <div class="col-3 p-3 text-center fw-light bg-laptopcard-select">
                    Todos
                </div>
                <div class="col-3 p-3 text-center fw-light">
                    Vinculados
                </div>
                <div class="col-3 p-3 text-center fw-light">
                    Não Vinculados
                </div>
                <%= link_to "Cadastrar", new_beneficiary_path, class: "fw-light text-dark text-decoration-none col-3 p-3 text-center" %>
            </div>
            <div class="container">
                <div class="row p-2 d-flex justify-content-evenly">
                    <% @beneficiaries.each do |beneficiary| %>
                        <div class="card p-2 col-3 bg-whitesmoke-titles border-0 mb-2 beneficiary-card" onclick="redirect(<%= beneficiary.id %>)" style="width: 10rem;">
                            <%= image_tag("person.png") %>                            
                            <div class="card-body">
                                <h5 class="card-title"><%= beneficiary.name.split(" ").first%></h5>
                                <p class="card-text fs-6">Vinculado à: <%=linked?(beneficiary)%></p>
                            </div>
                        </div>
                    <% end %>
                </div>

            </div>
        </div>
        
    </div>
</section>


<script>

    function redirect(id) {
        var a = document.createElement("a")
        a.href = "beneficiaries/"+id
        a.click()
    }

    function print(object) {
        console.log(object);
    }

</script>

app/views/beneficiaries/new.html.erb
<section class="container-fluid p-5">
    <div class="row h-100 justify-content-around">

        <div class="col-8 bg-whitesmoke p-0 border rounded">


            <div class="d-flex  bg-whitesmoke-titles"><p class="display-3 fw-lighter mx-auto my-auto">Cadastrar Beneficiário</p></div>
            <div class="container p-5">
                <div class="row">
                    <%= form_with model: @beneficiary do |form| %>
                    <div class="form-group mb-4">
                        <%= form.label :name, value: "Nome Completo" %><br>
                        <%= form.text_field :name, class: "form-control" %>
                        <% @beneficiary.errors.full_messages_for(:name).each do |message| %>
                        <div><%= message %></div>
                        <% end %>
                    </div>
                    <div class="form-group mb-4">
                        <%= form.label :contact_number, value: "Número de Contato" %><br>
                        <%= form.text_field :contact_number, class: "form-control " %>
                        <% @beneficiary.errors.full_messages_for(:contact_number).each do |message| %>
                        <div><%= message %></div>
                        <% end %>
                    </div>
                    <div class="form-group mb-4">
                        <%= form.label :identification_document, value: "Documento de Identificação" %><br>
                        <%= form.text_field :identification_document, class: "form-control " %>
                        <% @beneficiary.errors.full_messages_for(:identification_document).each do |message| %>
                        <div><%= message %></div>
                        <% end %>
                    </div>
                    <div class="form-group mb-4">
                        <%= form.label :identification_document, value: "Tipo de Contrato" %><br>
                        <%= form.select :contract_type, options_for_select([['Contratado', 'contratado'], ['Efetivo', 'efetivo']], selected: @beneficiary.contract_type), {}, class: "form-control form-select" %>                        
                        <% @beneficiary.errors.full_messages_for(:contract_type).each do |message| %>
                        <div><%= message %></div>
                        <% end %>
                    </div>
                    <div >
                        <%= form.submit:Cadastrar, class: "btn btn-secondary"  %>
                    </div>
                    <% end %>



                </div>
            </div>

        </div>
    </div>
</section>

app/views/beneficiaries/show.html.erb
<section class="container-fluid p-5">
    <div class="row h-100 justify-content-around">

        <div class="col-8 bg-whitesmoke p-0 border rounded">


            <div class="d-flex  bg-whitesmoke-titles">
                <% names = @beneficiary.name.split(" ") %>
                <% first_name = names.first %>
                <% last_name_initial = names.last.slice(0, 1) if names.length > 1 %>
                <h1 class="display-3 mx-auto"><i class="bi bi-person"></i> <%= "#{first_name} #{last_name_initial}." %></h1>                
            </div>
            <div class="container p-5">
                <div class="row">

                    <div class="form-group mb-4">
                        <label for="">Nome Completo</label>
                        <input type="email" class="form-control" value="<%= @beneficiary.name %>"  disabled>
                    </div>
                    <div class="form-group col-4 mb-4">
                        <label for="">Número de Contato</label>
                        <input type="email" class="form-control" value="<%= @beneficiary.contact_number %>"  disabled>
                    </div>
                    <div class="form-group col-4 mb-4">
                        <label for="">Documento de Identificação</label>
                        <input type="email" class="form-control" value="<%= @beneficiary.identification_document %>"  disabled>
                    </div>
                    <div class="form-group col-4 mb-4">
                        <label for="">Tipo de Contrato</label>
                        <input type="email" class="form-control" value="<%= @beneficiary.contract_type %>"  disabled>
                    </div>
                </div>
            </div>


            <div class="d-flex  bg-whitesmoke-titles">
                <h1 class="display-3 mx-auto"><i class="bi bi-laptop"></i> Notebook</h1>                
            </div>
            <div class="container p-5">
                <div class="row my-auto">
                    <%= image_tag "undefined.png", class: "col-4" %>
                    <div class="col-8">
                        <div class="row">
                            <div class="form-group mb-4">
                                <label for="">Número de Série</label>
                                <input type="email" class="form-control" value="NXAX0AL002129Z00"  disabled>
                            </div>
                            <div class="form-group col-4 mb-4">
                                <label for="">Número de Tombamento</label>
                                <input type="email" class="form-control" value="014-00251"  disabled>
                            </div>
                            <div class="form-group col-4 mb-4">
                                <label for="">Modelo</label>
                                <input type="email" class="form-control" value="A5-5432-5G"  disabled>
                            </div>
                            <div class="form-group col-4 mb-4">
                                <label for="">Data de aquisição</label>
                                <input type="email" class="form-control" value="00/00/0000"  disabled>
                            </div>
                            <div class="col-4 mb-4">
                                <button type="button" class="btn btn-secondary">Termo de aquisição <i class="bi bi-filetype-pdf"></i></button>
                            </div>

                        </div>
                    </div>
                </div>
            </div>


            <div class="d-flex  bg-whitesmoke-titles">
                <h1 class="display-3 mx-auto"><i class="bi bi-link-45deg"></i> Vínculos</h1>                
            </div>
            <div class="container p-5">
                <div class="row p-2 d-flex justify-content-evenly">
                    <div class="card p-2 col-4 bg-whitesmoke-titles border-0 mb-2 beneficiary-card" style="width: 10rem;">
                        <%= image_tag "silver.png" %>
                        <div class="card-body text-center">
                            <h5 class="card-title">01-00324</h5>
                            <p class="card-text fs-6">00/00/0000 00/00/0000</p>
                        </div>
                    </div>
                        <div class="card p-2 col-4 bg-whitesmoke-titles border-0 mb-2 beneficiary-card" style="width: 10rem;">
                        <%= image_tag "silver.png" %>
                        <div class="card-body text-center">
                            <h5 class="card-title">01-00324</h5>
                            <p class="card-text fs-6">00/00/0000 00/00/0000</p>
                        </div>
                    </div>
                        <div class="card p-2 col-4 bg-whitesmoke-titles border-0 mb-2 beneficiary-card" style="width: 10rem;">
                        <%= image_tag "silver.png" %>
                        <div class="card-body text-center">
                            <h5 class="card-title">01-00324</h5>
                            <p class="card-text fs-6">00/00/0000 00/00/0000</p>
                        </div>
                    </div>
                        <div class="card p-2 col-4 bg-whitesmoke-titles border-0 mb-2 beneficiary-card" style="width: 10rem;">
                        <%= image_tag "silver.png" %>
                        <div class="card-body text-center">
                            <h5 class="card-title">01-00324</h5>
                            <p class="card-text fs-6">00/00/0000 00/00/0000</p>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</section>

app/views/home/index.html.erb
<section class="container-fluid p-5">
    <div class="row h-100 justify-content-around">
        <div class="col-5 bg-whitesmoke p-0 border rounded">

            <p class="text-center display-6 bg-whitesmoke-titles">Notebooks</p>
            
            <div class=" mx-auto input-group mb-2 w-75 ">
                <input type="text" class="form-control bg-whitesmoke border">
                <span class="input-group-text bg-whitesmoke"><i class="bi bi-search"></i></span>
            </div>


            <div class="container">
                <div class="row p-2 d-flex justify-content-evenly">
                    <% @laptops.each do |laptop| %>
                        <a href="<%= laptop_path(laptop) %>" class="text-decoration-none card p-2 col-3 bg-whitesmoke-titles border-0 mb-2 laptop-card" style="width: 10rem;">
                            <%= image_tag laptop.model == "A515-54-5526" ? "silver.png" : "black.png" %>                            
                            <div class="card-body">
                                <h5 class="card-title"><%= laptop.listed_number[2] == "-" ? laptop.listed_number :  laptop.listed_number.insert(2, "-") %></h5>
                                <p class="card-text fs-6">Vinculado à: <%=linked?(laptop)%></p>
                            </div>
                        </a>
                    <% end %>
                </div>

            </div>
        </div>


        <div class="col-5 bg-whitesmoke p-0 border rounded">

            <p class="text-center display-6 bg-whitesmoke-titles">Beneficiários</p>
            
            <div class=" mx-auto input-group mb-2 w-75 ">
                <input type="text" class="form-control bg-whitesmoke border">
                <span class="input-group-text bg-whitesmoke"><i class="bi bi-search"></i></span>
            </div>


            <div class="container">
                <div class="row p-2 d-flex justify-content-evenly">
                    <% @beneficiaries.each do |beneficiary| %>
                        <a href="<%= beneficiary_path(beneficiary) %>" class=" text-decoration-none card p-2 col-3 bg-whitesmoke-titles border-0 mb-2" style="width: 10rem;">
                            <%= image_tag "person.png" %>
                            <div class="card-body">
                                <% names = beneficiary.name.split(" ") %>
                                <% first_name = names.first %>
                                <% last_name_initial = names.last.slice(0, 1) if names.length > 1 %>          
                                <h5 class="card-title"><%= "#{first_name} #{last_name_initial}." %></h5>
                                <p class="card-text fs-6">Vinculado à: <%=linked?(beneficiary)%></p>
                            </div>
                        </a>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/laptops/index.html.erb
<section class="container-fluid p-5">
    <div class="row h-100 justify-content-around">
        <div class="col-5 bg-whitesmoke p-0 border rounded">
            <div class="d-flex  bg-whitesmoke-titles">
                <div class="col-3 p-3 text-center fw-light bg-laptopcard-select">
                    Todos
                </div>
                <div class="col-3 p-3 text-center fw-light">
                    Vinculados
                </div>
                <div class="col-3 p-3 text-center fw-light">
                    Não Vinculados
                </div>
                <%= link_to "Cadastrar", new_laptop_path, class: "fw-light text-dark text-decoration-none col-3 p-3 text-center" %>
            </div>
            <div class="container">
                <div class="row p-2 d-flex justify-content-evenly">
                    <% @laptops.each do |laptop| %>
                        <div class="card p-2 col-3 bg-whitesmoke-titles border-0 mb-2 laptop-card" onclick="redirect(<%= laptop.id %>)" style="width: 10rem;">
                            <%= image_tag laptop.model == "A515-54-5526" ? "silver.png" : "black.png" %>                            
                            <div class="card-body">
                                <h5 class="card-title"><%=  laptop.listed_number[2] == "-" ? laptop.listed_number :  laptop.listed_number.insert(2, "-") %></h5>
                                <p class="card-text fs-6">Vinculado à: <%= linked? laptop %></p>
                            </div>
                        </div>
                    <% end %>
                </div>

            </div>
        </div>
        
    </div>
</section>


<script>

    function redirect(id) {
        var a = document.createElement("a")
        a.href = "laptops/"+id
        a.click()
    }

    function print(object) {
        console.log(object);
    }

</script>

app/views/laptops/new.html.erb
<section class="container-fluid p-5">
    <div class="row h-100 justify-content-around">

        <div class="col-8 bg-whitesmoke p-0 border rounded">


            <div class="d-flex  bg-whitesmoke-titles"><p class="display-3 fw-lighter mx-auto my-auto">Cadastrar Notebook</p></div>
            <div class="container p-5">
                <div class="row">
                    <%= form_with model: @laptop do |form| %>
                    <div class="form-group mb-4">
                        <%= form.label :serial_number, value: "Número de Série" %><br>
                        <%= form.text_field :serial_number, class: "form-control" %>
                        <% @laptop.errors.full_messages_for(:serial_number).each do |message| %>
                        <div><%= message %></div>
                        <% end %>
                    </div>
                    <div class="form-group mb-4">
                        <%= form.label :listed_number, value: "Número de Tombamento" %><br>
                        <%= form.text_field :listed_number, class: "form-control " %>
                        <% @laptop.errors.full_messages_for(:listed_number).each do |message| %>
                        <div><%= message %></div>
                        <% end %>
                    </div>
                    <div class="form-group mb-4">
                        <%= form.label :identification_document, value: "Modelo" %><br>
                        <%= form.select :model, options_for_select([['Prata', 'A515-54-5526'], ['Preto', 'A515-54-55L0']], selected: @laptop.model), {}, class: "form-control form-select" %>                        
                        <% @laptop.errors.full_messages_for(:model).each do |message| %>
                        <div><%= message %></div>
                        <% end %>
                    </div>
                    <div >
                        <%= form.submit  %>
                    </div>
                    <% end %>



                </div>
            </div>

        </div>
    </div>
</section>

app/views/laptops/show.html.erb
<section class="container-fluid p-5">
    <div class="row h-100 justify-content-around">

        <div class="col-8 bg-whitesmoke p-0 border rounded">

            <div class="d-flex  bg-whitesmoke-titles">
                <h1 class="display-3 mx-auto"><i class="bi bi-laptop"></i> <%=  @laptop.listed_number.insert(2, "-")  %></h1>                
            </div>
            <div class="container p-5">
                <div class="row my-auto">
                    <%= image_tag @laptop.model == "A515-54-5526" ? "silver.png" : "black.png", class: "col-4" %>
                    <div class="col-8">
                        <div class="row">
                            <div class="form-group mb-4">
                                <label for="">Número de Série</label>
                                <input type="text" class="form-control" value="<%=  @laptop.serial_number %>"  disabled>
                            </div>
                            <div class="form-group col-4 mb-4">
                                <label for="">Número de Tombamento</label>
                                <input type="text" class="form-control" value="<%=  @laptop.listed_number[2] == "-" ? @laptop.listed_number :  @laptop.listed_number.insert(2, "-") %>"  disabled>
                            </div>
                            <div class="form-group col-4 mb-4">
                                <label for="">Modelo</label>
                                <input type="text" class="form-control" value="<%=  @laptop.model %>"  disabled>
                            </div>
                            <div class="form-group col-4 mb-4">
                                <label for="">Estado</label>
                                <input type="text" class="form-control" value=""  disabled>
                            </div>


                        </div>
                    </div>
                </div>
            </div>

            <div class="d-flex  bg-whitesmoke-titles">
                <h1 class="display-3 mx-auto"><i class="bi bi-person"></i> Beneficiário</h1>                
            </div>
            <div class="container p-5">
                <div class="row my-auto">
                    <%= image_tag "person.png", class: "col-4" %>
                    <div class="col-8">
                        <div class="row">
                            <div class="form-group mb-4">
                                <label for="">Nome Completo</label>
                                <input type="text" class="form-control" value="NXAX0AL002129Z00"  disabled>
                            </div>
                            <div class="form-group col-4 mb-4">
                                <label for="">Número de Contato</label>
                                <input type="text" class="form-control" value="014-00251"  disabled>
                            </div>
                            <div class="form-group col-4 mb-4">
                                <label for="">Documento</label>
                                <input type="text" class="form-control" value="A5-5432-5G"  disabled>
                            </div>
                            <div class="form-group col-4 mb-4">
                                <label for="">Tipo de Contrato</label>
                                <input type="text" class="form-control" value="00/00/0000"  disabled>
                            </div>
                            <div class="col-4 mb-4">
                                <button type="button" class="btn btn-secondary">Termo de aquisição <i class="bi bi-filetype-pdf"></i></button>
                            </div>

                        </div>
                    </div>
                </div>
            </div>


            <div class="d-flex  bg-whitesmoke-titles">
                <h1 class="display-3 mx-auto"><i class="bi bi-link-45deg"></i> Vínculos</h1>                
            </div>
            <div class="container p-5">
                <div class="row p-2 d-flex justify-content-evenly">
                    <div class="card p-2 col-4 bg-whitesmoke-titles border-0 mb-2 beneficiary-card" style="width: 10rem;">
                        <%= image_tag "silver.png" %>
                        <div class="card-body text-center">
                            <h5 class="card-title">01-00324</h5>
                            <p class="card-text fs-6">00/00/0000 00/00/0000</p>
                        </div>
                    </div>
                        <div class="card p-2 col-4 bg-whitesmoke-titles border-0 mb-2 beneficiary-card" style="width: 10rem;">
                        <%= image_tag "silver.png" %>
                        <div class="card-body text-center">
                            <h5 class="card-title">01-00324</h5>
                            <p class="card-text fs-6">00/00/0000 00/00/0000</p>
                        </div>
                    </div>
                        <div class="card p-2 col-4 bg-whitesmoke-titles border-0 mb-2 beneficiary-card" style="width: 10rem;">
                        <%= image_tag "silver.png" %>
                        <div class="card-body text-center">
                            <h5 class="card-title">01-00324</h5>
                            <p class="card-text fs-6">00/00/0000 00/00/0000</p>
                        </div>
                    </div>
                        <div class="card p-2 col-4 bg-whitesmoke-titles border-0 mb-2 beneficiary-card" style="width: 10rem;">
                        <%= image_tag "silver.png" %>
                        <div class="card-body text-center">
                            <h5 class="card-title">01-00324</h5>
                            <p class="card-text fs-6">00/00/0000 00/00/0000</p>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaptopManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  </head>

  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light p-4 bg-whitesmoke">
            <a class="navbar-brand" href="/">Notebook Manager</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/beneficiaries">Beneficiários <i class="bi bi-person"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/laptops">Notebooks <i class="bi bi-laptop"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/links">Vínculos <i class="bi bi-link-45deg"></i></a>
                </li>
                </ul>
            </div>
            <a class="nav-link fixed-end" href="#"><i class="bi bi-info-circle"></i></a>

        </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/links/index.html.erb
<section class="container-fluid p-5">
    <div class="row h-100 justify-content-around">
        <div class="col-10 bg-whitesmoke p-0 border rounded">
            <div class="d-flex  bg-whitesmoke-titles">
                <div class="col-3 p-3 text-center fw-light bg-laptopcard-select">
                    Todos
                </div>
                <div class="col-3 p-3 text-center fw-light">
                    Ativos
                </div>
                <div class="col-3 p-3 text-center fw-light">
                    Finalizados
                </div>
                <%= link_to "Criar Vínculo", new_link_path, class: "fw-light text-dark text-decoration-none col-3 p-3 text-center" %>
            </div>
            <div class="container">
                <div class="row p-2 d-flex justify-content-evenly">
                    <% @links.each do |link| %>
                        <% names = link.beneficiary.name.split(" ") %>
                        <% first_name = names.first %>
                        <% last_name_initial = names.last.slice(0, 1) if names.length > 1 %>
                        <a class="text-decoration-none card p-2 col-6 bg-whitesmoke-titles border-0 mb-2 beneficiary-card" style="width: 15rem;">
                            <%= image_tag("link.png") %>                            
                            <div class="card-body">
                                <h5 class="card-title fs-6 text-center"><%= "#{first_name} #{last_name_initial}." %> <i class="bi bi-link-45deg"></i> <%= link.laptop.listed_number.insert(2, "-") %></h5>
                                <p class="card-text fs-6">Estado: <%= link.end_date == nil ? "Ativo" : "Finalizado" %></p>
                            </div>
                        </a>
                    <% end %>
                </div>

            </div>
        </div>
        
    </div>
</section>


<script>

    function redirect(id) {
        var a = document.createElement("a")
        a.href = "beneficiaries/"+id
        a.click()
    }

    function print(object) {
        console.log(object);
    }

</script>